export const ACCOUNT_INFO_FORM_FIELD_KEY = {
  FULLNAME_NAME: 'FULLNAME_NAME',
  COMPANY_INFO_FORM_FIELDS: 'COMPANY_INFO_FORM_FIELDS',
  COMPANY_NAME: 'COMPANY_NAME',
  COMPANY_INN: 'COMPANY_INN',
  POSITION_IN_COMPANY: 'POSITION_IN_COMPANY',
};
