import { ADMIN_REVISION_REVIEW_ITEM_DATA_NAME } from './admin-revision-review-item.constant';

export const performAdminRevisionReviewItemData = (row) => ({
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.DESCRIPRION]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.DESCRIPRION],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.FILE_DESCRIPRION]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.FILE_DESCRIPRION],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.REVIEW]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.REVIEW],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.FILE_REVIEW]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.FILE_REVIEW],
});
