import { ADMIN_REVISION_REVIEW_ITEM_DATA_NAME } from './admin-revision-review-item.constant';
import { convertFormatDate } from '../../lib/common/convert/convert.core';

export const performAdminRevisionReviewItemData = (row) => ({
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.DESCRIPRION]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.DESCRIPRION],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.FILE_DESCRIPRION]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.FILE_DESCRIPRION],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.REVIEW]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.REVIEW],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.FILE_REVIEW]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.FILE_REVIEW],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.STATUS]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.STATUS],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.PRICE]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.PRICE],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.YEAR]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.YEAR],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATE_DATE]: convertFormatDate(
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATE_DATE],
  ),
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.COMPANY]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.COMPANY],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.COMPANY_ID]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.COMPANY][
      ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.COMPANY_ID
    ],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.COMPANY_NAME]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.COMPANY][
      ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.COMPANY_NAME
    ],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.COMPANY_INN]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.COMPANY][
      ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.COMPANY_INN
    ],

  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATOR]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATOR],

  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATOR_LOGIN]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATOR][
      ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATOR_LOGIN
    ],

  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATOR_FIRSTNAME]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATOR][
      ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATOR_FIRSTNAME
    ],
  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATOR_LASTNAME]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATOR][
      ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.CREATOR_LASTNAME
    ],

  [ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.REVISION_COMPANIES]:
    row[ADMIN_REVISION_REVIEW_ITEM_DATA_NAME.REVISION_COMPANIES],
});
