export const COMPANY_MEMBERS_ACTION_TYPE = {
  COMPANY_MEMBERS_LOAD_REQUEST_PENDING:
    'COMPANY_MEMBERS_ACTION_TYPE.COMPANY_MEMBERS_LOAD_REQUEST_PENDING',
  COMPANY_MEMBERS_LOAD_REQUEST_SUCCESS:
    'COMPANY_MEMBERS_ACTION_TYPE.COMPANY_MEMBERS_LOAD_REQUEST_SUCCESS',
  COMPANY_MEMBERS_LOAD_REQUEST_ERROR:
    'COMPANY_MEMBERS_ACTION_TYPE.COMPANY_MEMBERS_LOAD_REQUEST_ERROR',
  COMPANY_INFO_LOAD_REQUEST_SUCCESS:
    'COMPANY_MEMBERS_ACTION_TYPE.COMPANY_INFO_LOAD_REQUEST_SUCCESS',
  DELETE_USER_COMPANY_REQUEST_SUCCESS:
    'COMPANY_MEMBERS_ACTION_TYPE.DELETE_USER_COMPANY_REQUEST_SUCCESS',
};

export const COMPANY_MEMBERS_DATA_NAME = {
  COMPANY_USER_ID: 'id',
  USER_AVATAR: 'avatar',
  USER_NAME: 'name',
  USER_POSITION: 'position',
  USER_ROLE_INFO: 'roleInfo',
  USER_ROLE_NAME: 'roleName',
  USER_ROLE_ID: 'roleId',
  IN_COMPANY_DATE: 'inTheCompany',
};
export const COMPANY_MEMBERS_DATA_KEY = {
  COMPANY_USER_ID: 'companyUserId',
  USER_AVATAR: 'avatar',
  USER_NAME: 'name',
  USER_POSITION: 'position',
  USER_ROLE: 'role',
  IN_COMPANY_DATE: 'inTheCompany',
};

export const COMPANY_INFO_DATA_NAME = {
  COMPANY_NAME: 'companyName',
};
export const COMPANY_INFO_DATA_KEY = {
  COMPANY_NAME: 'name',
};

export const COMPANY_MEMBERS_FORM_FIELD_NAME = {
  USER_ROLE_ID: 'roleId',
  INVITE_USER_EMAIL: 'inviteUserEmail',
};
