export const COMPANY_MEMBERS_ACTION_TYPE = {
  COMPANY_MEMBERS_LOAD_REQUEST_PENDING:
    'COMPANY_MEMBERS_ACTION_TYPE.COMPANY_MEMBERS_LOAD_REQUEST_PENDING',
  COMPANY_MEMBERS_LOAD_REQUEST_SUCCESS:
    'COMPANY_MEMBERS_ACTION_TYPE.COMPANY_MEMBERS_REQUEST_LOAD_REQUEST_SUCCESS',
  COMPANY_MEMBERS_LOAD_REQUEST_ERROR:
    'COMPANY_MEMBERS_ACTION_TYPE.COMPANY_MEMBERS_LOAD_REQUEST_ERROR',
};
