export const COUNTERPARTY_ACTION_TYPE = {
  COUNTERPARTY_LOAD_REQUEST_PENDING:
    'COUNTERPARTY_ACTION_TYPE.COUNTERPARTY_LOAD_REQUEST_PENDING',
  COUNTERPARTY_LOAD_REQUEST_SUCCESS:
    'COUNTERPARTY_ACTION_TYPE.COUNTERPARTY_REQUEST_LOAD_REQUEST_SUCCESS',
  COUNTERPARTY_LOAD_REQUEST_ERROR:
    'COUNTERPARTY_ACTION_TYPE.COUNTERPARTY_LOAD_REQUEST_ERROR',
};
