export const DASHBOARD_ADMIN_ACTION_TYPE = {
  DASHBOARD_ADMIN_LOAD_REQUEST_PENDING:
    'DASHBOARD_ADMIN_ACTION_TYPE.DASHBOARD_ADMIN_LOAD_REQUEST_PENDING',
  DASHBOARD_ADMIN_LOAD_REQUEST_SUCCESS:
    'DASHBOARD_ADMIN_ACTION_TYPE.DASHBOARD_ADMIN_REQUEST_LOAD_REQUEST_SUCCESS',
  DASHBOARD_ADMIN_LOAD_REQUEST_ERROR:
    'DASHBOARD_ADMIN_ACTION_TYPE.DASHBOARD_ADMIN_LOAD_REQUEST_ERROR',
};
