import { SETTINGS_2FA_FORM_FIELD_KEY } from './frame/settings-2fa-form';

export const SETTINGS_2FA_FIELD_NAME = {
  PHONE_NUMBER: 'phoneNumber',
};

export const SETTINGS_2FA_FORM_FIELD_NAME = {
  [SETTINGS_2FA_FORM_FIELD_KEY.PHONE_NUMBER]:
    SETTINGS_2FA_FIELD_NAME.PHONE_NUMBER,
};

export const SETTINGS_2FA_ACTION_TYPE = {
  SETTINGS_2FA_FORM_UPLOAD_PENDING:
    'SIGNUP_ACTION_TYPE.SETTINGS_2FA_FORM_UPLOAD_PENDING',
  SETTINGS_2FA_FORM_UPLOAD_SUCCESS:
    'SIGNUP_ACTION_TYPE.SETTINGS_2FA_FORM_UPLOAD_SUCCESS',
  SETTINGS_2FA_FORM_UPLOAD_ERROR:
    'SIGNUP_ACTION_TYPE.SETTINGS_2FA_FORM_UPLOAD_ERROR',
};

export const SETTINGS_2FA_DATA_NAME = {
  PHONE_NUMBER: 'phone',
};
