import { COMPANY_ACCOUNT_ITEM_KONTRAGENT_DATA_NAME } from './company-account-item-kontragent.constant';

export const convertCompanyAccountItemKontragentList = (d) => {
  return d.map((company) => ({
    [COMPANY_ACCOUNT_ITEM_KONTRAGENT_DATA_NAME.ID]:
      company[COMPANY_ACCOUNT_ITEM_KONTRAGENT_DATA_NAME.ID],
    [COMPANY_ACCOUNT_ITEM_KONTRAGENT_DATA_NAME.NAME]:
      company[COMPANY_ACCOUNT_ITEM_KONTRAGENT_DATA_NAME.NAME],
    [COMPANY_ACCOUNT_ITEM_KONTRAGENT_DATA_NAME.INN]:
      company[COMPANY_ACCOUNT_ITEM_KONTRAGENT_DATA_NAME.CONTRACTOR][
        COMPANY_ACCOUNT_ITEM_KONTRAGENT_DATA_NAME.INN
      ],
  }));
};

export const convertCompanyAccountItemKontragentCreateFormData = (data) => ({
  [COMPANY_ACCOUNT_ITEM_KONTRAGENT_DATA_NAME.NAME]:
    data[COMPANY_ACCOUNT_ITEM_KONTRAGENT_DATA_NAME.NAME],
  [COMPANY_ACCOUNT_ITEM_KONTRAGENT_DATA_NAME.INN]:
    data[COMPANY_ACCOUNT_ITEM_KONTRAGENT_DATA_NAME.INN],
});
