import { COMPANY_SETTINGS_FORM_FIELD_KEY } from './frame/fields';

export const COMPANY_SETTINGS_FIELD_NAME = {
  NAME: 'name',
  ENTITY: 'entity',
  OWNER: 'owner',
  ORGANIZATION: 'organization',
};

export const COMPANY_SETTINGS_FORM_FIELD_NAME = {
  [COMPANY_SETTINGS_FORM_FIELD_KEY.NAME]: COMPANY_SETTINGS_FIELD_NAME.NAME,
  [COMPANY_SETTINGS_FORM_FIELD_KEY.ENTITY]: COMPANY_SETTINGS_FIELD_NAME.ENTITY,
  [COMPANY_SETTINGS_FORM_FIELD_KEY.OWNER]: COMPANY_SETTINGS_FIELD_NAME.OWNER,
  [COMPANY_SETTINGS_FORM_FIELD_KEY.ORGANIZATION]: COMPANY_SETTINGS_FIELD_NAME.ORGANIZATION,
};
