import { ADMIN_REVISION_INFO_DATA_NAME } from './admin-revision-info.constant';

export const performAdminRevisionInfoData = (data) => ({
  [ADMIN_REVISION_INFO_DATA_NAME.REVIEW]:
    data[ADMIN_REVISION_INFO_DATA_NAME.REVIEW],
  [ADMIN_REVISION_INFO_DATA_NAME.STATUS]:
    data[ADMIN_REVISION_INFO_DATA_NAME.STATUS],
  [ADMIN_REVISION_INFO_DATA_NAME.PRICE]:
    data[ADMIN_REVISION_INFO_DATA_NAME.PRICE],
  [ADMIN_REVISION_INFO_DATA_NAME.FILE_REVIEW]:
    data[ADMIN_REVISION_INFO_DATA_NAME.FILE_REVIEW],
});
