import { COMPANY_ACCOUNT_ITEM_KONTRAGENT_ITEM_INFO_DATA_NAME as DATA_NAME } from './company-account-item-kontragent-item-info.constant';

export function covertCompanyAccountItemKontragentItemInfoData(data) {
  return {
    [DATA_NAME.ID]: data[DATA_NAME.ID],
    [DATA_NAME.KONTRAGENT_NAME]: data[DATA_NAME.NAME],
    [DATA_NAME.COMMENT]: data[DATA_NAME.COMMENT],
    [DATA_NAME.EMAIL]: data[DATA_NAME.EMAIL],
    [DATA_NAME.RATING]: data[DATA_NAME.RATING],
    [DATA_NAME.COMPANY_ID]: data[DATA_NAME.CONTRACTOR][DATA_NAME.ID],
    [DATA_NAME.INN]: data[DATA_NAME.CONTRACTOR][DATA_NAME.INN],
    [DATA_NAME.COMPANY_NAME]: data[DATA_NAME.CONTRACTOR][DATA_NAME.NAME],
    [DATA_NAME.COMPANY_REGISTERED]:
      data[DATA_NAME.CONTRACTOR][DATA_NAME.COMPANY_REGISTERED],
  };
}
