import { ADMIN_BILL_INFO_DATA_NAME } from './admin-bill-info.constant';

export const performAdminBillInfoData = (data) => ({
  [ADMIN_BILL_INFO_DATA_NAME.ID]: data[ADMIN_BILL_INFO_DATA_NAME.ID],
  [ADMIN_BILL_INFO_DATA_NAME.STATUS]: data[ADMIN_BILL_INFO_DATA_NAME.STATUS],
  [ADMIN_BILL_INFO_DATA_NAME.AMOUNT]: data[ADMIN_BILL_INFO_DATA_NAME.AMOUNT],
  [ADMIN_BILL_INFO_DATA_NAME.FILES]: data[ADMIN_BILL_INFO_DATA_NAME.FILES],
  [ADMIN_BILL_INFO_DATA_NAME.DESCRIPTION]:
    data[ADMIN_BILL_INFO_DATA_NAME.DESCRIPTION],
  [ADMIN_BILL_INFO_DATA_NAME.NAME]:
    data[ADMIN_BILL_INFO_DATA_NAME.COMPANY][ADMIN_BILL_INFO_DATA_NAME.NAME],
  [ADMIN_BILL_INFO_DATA_NAME.INN]:
    data[ADMIN_BILL_INFO_DATA_NAME.COMPANY][ADMIN_BILL_INFO_DATA_NAME.INN],
});
