import { COMPANY_ACCOUNT_KONTRAGENTS_DATA_NAME } from './company-account-kontragents.constant';

export const performCompanyAccountKontragentsRowData = (rowData) => {
  return rowData.map((company) => ({
    [COMPANY_ACCOUNT_KONTRAGENTS_DATA_NAME.ID]: company[COMPANY_ACCOUNT_KONTRAGENTS_DATA_NAME.ID],
    [COMPANY_ACCOUNT_KONTRAGENTS_DATA_NAME.NAME]: company[COMPANY_ACCOUNT_KONTRAGENTS_DATA_NAME.NAME],
    [COMPANY_ACCOUNT_KONTRAGENTS_DATA_NAME.INN]:
      company[COMPANY_ACCOUNT_KONTRAGENTS_DATA_NAME.CONTRACTOR][COMPANY_ACCOUNT_KONTRAGENTS_DATA_NAME.INN],
  }));
};

export const convertCompanyAccountKontragentCreateFormData = (data) => ({
  [COMPANY_ACCOUNT_KONTRAGENTS_DATA_NAME.NAME]: data[COMPANY_ACCOUNT_KONTRAGENTS_DATA_NAME.NAME],
  [COMPANY_ACCOUNT_KONTRAGENTS_DATA_NAME.INN]: data[COMPANY_ACCOUNT_KONTRAGENTS_DATA_NAME.INN],
});
