export const CAPTCHA_ACTION_TYPE = {
  CAPTCHA_LOAD_PENDING: 'CAPTCHA_ACTION_TYPE.CAPTCHA_LOAD_PENDING',
  CAPTCHA_LOAD_SUCCESS: 'CAPTCHA_ACTION_TYPE.CAPTCHA_LOAD_SUCCESS',
  CAPTCHA_LOAD_ERROR: 'CAPTCHA_ACTION_TYPE.CAPTCHA_LOAD_ERROR',
  CAPTCHA_LOAD_RESET: 'CAPTCHA_ACTION_TYPE.CAPTCHA_LOAD_RESET',
};
