export const BALANCE_ACTION_TYPE = {
  BALANCE_LOAD_REQUEST_PENDING:
    'BALANCE_ACTION_TYPE.BALANCE_LOAD_REQUEST_PENDING',
  BALANCE_LOAD_REQUEST_SUCCESS:
    'BALANCE_ACTION_TYPE.BALANCE_REQUEST_LOAD_REQUEST_SUCCESS',
  BALANCE_LOAD_REQUEST_ERROR:
    'BALANCE_ACTION_TYPE.BALANCE_LOAD_REQUEST_ERROR',
};
