export const INFORMATION_ACTION_TYPE = {
  INFORMATION_LOAD_REQUEST_PENDING:
    'INFORMATION_ACTION_TYPE.INFORMATION_LOAD_REQUEST_PENDING',
  INFORMATION_LOAD_REQUEST_SUCCESS:
    'INFORMATION_ACTION_TYPE.INFORMATION_REQUEST_LOAD_REQUEST_SUCCESS',
  INFORMATION_LOAD_REQUEST_ERROR:
    'INFORMATION_ACTION_TYPE.INFORMATION_LOAD_REQUEST_ERROR',
};
