import { SETTINGS_FORM_CHANGE_EMAIL_FIELD_KEY } from './frame';

export const SETTINGS_EMAIL_FIELD_NAME = {
  EMAIL: 'email',
  PASSWORD: 'password',
};

export const SETTINGS_FORM_CHANGE_EMAIL_FIELD_NAME = {
  [SETTINGS_FORM_CHANGE_EMAIL_FIELD_KEY.EMAIL]: SETTINGS_EMAIL_FIELD_NAME.EMAIL,
  [SETTINGS_FORM_CHANGE_EMAIL_FIELD_KEY.PASSWORD]:
    SETTINGS_EMAIL_FIELD_NAME.PASSWORD,
};
