import { SETTINGS_FORM_CHANGE_EMAIL_FIELD_KEY } from './frame';

export const SETTINGS_EMAIL_FIELD_NAME = {
  EMAIL: 'email',
  PASSWORD: 'password',
};

export const SETTINGS_FORM_CHANGE_EMAIL_FIELD_NAME = {
  [SETTINGS_FORM_CHANGE_EMAIL_FIELD_KEY.EMAIL]: SETTINGS_EMAIL_FIELD_NAME.EMAIL,
  [SETTINGS_FORM_CHANGE_EMAIL_FIELD_KEY.PASSWORD]:
    SETTINGS_EMAIL_FIELD_NAME.PASSWORD,
};

export const SETTINGS_EMAIL_ACTION_TYPE = {
  SETTINGS_FORM_CHANGE_EMAIL_UPLOAD_SUCCESS:
    'SETTINGS_FORM_CHANGE_EMAIL_UPLOAD_SUCCESS',
  SETTINGS_FORM_CHANGE_EMAIL_UPLOAD_PENDING:
    'SETTINGS_FORM_CHANGE_EMAIL_UPLOAD_PENDING',
  SETTINGS_FORM_CHANGE_EMAIL_UPLOAD_ERROR:
    'SETTINGS_FORM_CHANGE_EMAIL_UPLOAD_ERROR',
  SETTINGS_FORM_CHANGE_EMAIL_UPLOAD_RESET:
    'SETTINGS_FORM_CHANGE_EMAIL_UPLOAD_RESET',
  SETTINGS_EMAIL_GET_EMAIL_SUCCESS: 'SETTINGS_EMAIL_GET_EMAIL_SUCCESS',
  SETTINGS_EMAIL_GET_EMAIL_PENDING: 'SETTINGS_EMAIL_GET_EMAIL_PENDING',
  SETTINGS_EMAIL_GET_EMAIL_ERROR: 'SETTINGS_EMAIL_GET_EMAIL_ERROR',
  SETTINGS_EMAIL_GET_EMAIL_RESET: 'SETTINGS_EMAIL_GET_EMAIL_RESET',
};

export const SETTINGS_EMAIL_DATA_NAME = {
  EMAIL: 'email',
};
