export const ARBITRATION_REQUESTS_LIST_ACTION_TYPE = {
  ARBITRATION_REQUESTS_LIST_LOAD_REQUEST_PENDING:
    'ARBITRATION_REQUESTS_LIST_ACTION_TYPE.ARBITRATION_REQUESTS_LIST_LOAD_REQUEST_PENDING',
  ARBITRATION_REQUESTS_LIST_LOAD_REQUEST_SUCCESS:
    'ARBITRATION_REQUESTS_LIST_ACTION_TYPE.ARBITRATION_REQUESTS_LIST_REQUEST_LOAD_REQUEST_SUCCESS',
  ARBITRATION_REQUESTS_LIST_LOAD_REQUEST_ERROR:
    'ARBITRATION_REQUESTS_LIST_ACTION_TYPE.ARBITRATION_REQUESTS_LIST_LOAD_REQUEST_ERROR',
};
