export const revisionStatusType = {
  1: 'COMMON.REVISION.STATUS_TYPE.NEW',
  2: 'COMMON.REVISION.STATUS_TYPE.PROGRESS',
  3: 'COMMON.REVISION.STATUS_TYPE.DONE',
  4: 'COMMON.REVISION.STATUS_TYPE.PAY',
  5: 'COMMON.REVISION.STATUS_TYPE.PAID',
};

export const referalAchieventStatusType = {
  0: 'COMMON.REFERAL.STATUS.SIGNUP',
  1: 'COMMON.REFERAL.STATUS.PAYMENT',
};
