export const revisionStatusType = {
  1: 'COMMON.REVISION.STATUS_TYPE.NEW',
  2: 'COMMON.REVISION.STATUS_TYPE.PROGRESS',
  3: 'COMMON.REVISION.STATUS_TYPE.DONE',
  4: 'COMMON.REVISION.STATUS_TYPE.PAY',
  5: 'COMMON.REVISION.STATUS_TYPE.PAID',
};

export const referalPaymentStatusType = {
  0: 'COMMON.REFERAL.STATUS.NEW_REFERAL',
  1: 'COMMON.REFERAL.STATUS.ADDED_KONTRAGENT_INFO',
  2: 'COMMON.REFERAL.STATUS.USER_TO_REVISION_KONTRAGENT_PAY',
  3: 'COMMON.REFERAL.STATUS.USER_TO_REVISION_SELF_PAY',
};

export const paymentType = {
  1: 'COMMON.PAYMENT.STATUS.IN',
  2: 'COMMON.PAYMENT.STATUS.OUT',
  3: 'COMMON.PAYMENT.STATUS.BILL_IN',
  4: 'COMMON.PAYMENT.STATUS.PAY_IN',
  5: 'COMMON.PAYMENT.STATUS.REVISION_KONTRAGENT',
  6: 'COMMON.PAYMENT.STATUS.REVISION_SELF',
};

export const companyMemberType = {
  1: 'COMMON.COMPANY_MEMBER_ROLE.OWNER',
  2: 'COMMON.COMPANY_MEMBER_ROLE.EMPLOYEE',
};
