import { AUTH_RECOVERY_ACCOUNT_UPDATE_PASSWORD_DATA_NAME } from './auth-recovery-account-update-password.constant';

export const convertAuthRecoveryAccountUpdatePasswordFormData = (data) => ({
  [AUTH_RECOVERY_ACCOUNT_UPDATE_PASSWORD_DATA_NAME.CODE]: data[AUTH_RECOVERY_ACCOUNT_UPDATE_PASSWORD_DATA_NAME.CODE],
  [AUTH_RECOVERY_ACCOUNT_UPDATE_PASSWORD_DATA_NAME.PASSWORD]: data[AUTH_RECOVERY_ACCOUNT_UPDATE_PASSWORD_DATA_NAME.PASSWORD],
});
