export const MY_SUPPORT_REQUESTS_LIST_ACTION_TYPE = {
  MY_SUPPORT_REQUESTS_LIST_LOAD_REQUEST_PENDING:
    'MY_SUPPORT_REQUESTS_LIST_ACTION_TYPE.MY_SUPPORT_REQUESTS_LIST_LOAD_REQUEST_PENDING',
  MY_SUPPORT_REQUESTS_LIST_LOAD_REQUEST_SUCCESS:
    'MY_SUPPORT_REQUESTS_LIST_ACTION_TYPE.MY_SUPPORT_REQUESTS_LIST_REQUEST_LOAD_REQUEST_SUCCESS',
  MY_SUPPORT_REQUESTS_LIST_LOAD_REQUEST_ERROR:
    'MY_SUPPORT_REQUESTS_LIST_ACTION_TYPE.MY_SUPPORT_REQUESTS_LIST_LOAD_REQUEST_ERROR',
};
