import { COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME } from './company-account-bill-item.constant';

export const performCompanyAccountBillItemData = (row) => ({
  [COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.ID]:
    row[COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.ID],

  [COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.AMOUNT]:
    row[COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.AMOUNT],
  [COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.FILES]:
    row[COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.FILES],
  [COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.DESCRIPTION]:
    row[COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.DESCRIPTION],
  [COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.NAME]:
    row[COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.COMPANY][
      COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.NAME
    ],
  [COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.INN]:
    row[COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.COMPANY][
      COMPANY_ACCOUNT_BILL_ITEM_DATA_NAME.INN
    ],
});
