export const AUTH_VERIFICATION_PHONE_ACTION_TYPE = {
  AUTH_FORM_VERIFICATION_PHONE_UPLOAD_PENDING:
    'AUTH_FORM_VERIFICATION_PHONE_UPLOAD_PENDING',
  AUTH_FORM_VERIFICATION_PHONE_UPLOAD_SUCCESS:
    'AUTH_FORM_VERIFICATION_PHONE_UPLOAD_SUCCESS',
  AUTH_FORM_VERIFICATION_PHONE_UPLOAD_ERROR:
    'AUTH_FORM_VERIFICATION_PHONE_UPLOAD_ERROR',
  AUTH_FORM_VERIFICATION_PHONE_UPLOAD_RESET:
    'AUTH_FORM_VERIFICATION_PHONE_UPLOAD_RESET',

  AUTH_FORM_VERIFICATION_PHONE_CONFIRM_UPLOAD_PENDING:
    'AUTH_FORM_VERIFICATION_PHONE_CONFIRM_UPLOAD_PENDING',
  AUTH_FORM_VERIFICATION_PHONE_CONFIRM_UPLOAD_SUCCESS:
    'AUTH_FORM_VERIFICATION_PHONE_CONFIRM_UPLOAD_SUCCESS',
  AUTH_FORM_VERIFICATION_PHONE_CONFIRM_UPLOAD_ERROR:
    'AUTH_FORM_VERIFICATION_PHONE_CONFIRM_UPLOAD_ERROR',
  AUTH_FORM_VERIFICATION_PHONE_CONFIRM_UPLOAD_RESET:
    'AUTH_FORM_VERIFICATION_PHONE_CONFIRM_UPLOAD_RESET',
};

import { AUTH_FORM_VERIFICATION_PHONE_CONFIRM_FIELD_KEY } from './frame/auth-form-verification-phone-confirm';

export const AUTH_VERIFICATION_PHONE_FIELD_NAME = {
  CODE: 'code',
};

export const AUTH_FORM_VERIFICATION_PHONE_CONFIRM_FIELD_NAME = {
  [AUTH_FORM_VERIFICATION_PHONE_CONFIRM_FIELD_KEY.CODE]:
    AUTH_VERIFICATION_PHONE_FIELD_NAME.CODE,
};
