export const AUTH_VERIFICATION_EMAIL_CONFIRM_ACTION_TYPE = {
  AUTH_VERIFICATION_EMAIL_CONFIRM_UPLOAD_PENDING:
    'AUTH_VERIFICATION_EMAIL_CONFIRM_UPLOAD_PENDING',
  AUTH_VERIFICATION_EMAIL_CONFIRM_UPLOAD_SUCCESS:
    'AUTH_VERIFICATION_EMAIL_CONFIRM_UPLOAD_SUCCESS',
  AUTH_VERIFICATION_EMAIL_CONFIRM_UPLOAD_ERROR:
    'AUTH_VERIFICATION_EMAIL_CONFIRM_UPLOAD_ERROR',
  AUTH_VERIFICATION_EMAIL_CONFIRM_UPLOAD_RESET:
    'AUTH_VERIFICATION_EMAIL_CONFIRM_UPLOAD_RESET',
};
