import { COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME } from './company-account-item-member-list.constant';

export const performCompanyAccountItemMemberListData = (row) => {
  return row[COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.LIST].map((member) => ({
    [COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.ID]:
      member[COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.ID],
    [COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.FIRSTNAME]:
      member[COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.USER][
      COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.FIRSTNAME
      ],
    [COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.LASTNAME]:
      member[COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.USER][
      COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.LASTNAME
      ],
    [COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.LOGIN]:
      member[COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.USER][
      COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.LOGIN
      ],
    [COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.ROLE]:
      member[COMPANY_ACCOUNT_ITEM_MEMBER_LIST_DATA_NAME.ROLE],
  }));
};
