import { COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME } from './company-account-kontragent-info.constant';

export const performCompanyAccountKontragentItemInfoData = (rowData) => ({
  [COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.ID]: rowData[COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.ID],
  [COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.KONTRAGENT_NAME]: rowData[COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.NAME],
  [COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.COMPANY_ID]:
    rowData[COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.CONTRACTOR][COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.ID],
  [COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.INN]:
    rowData[COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.CONTRACTOR][COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.INN],
  [COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.COMPANY_NAME]:
    rowData[COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.CONTRACTOR][COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.NAME],
  [COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.COMPANY_REGISTERED]:
    rowData[COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.CONTRACTOR][COMPANY_ACCOUNT_KONTRAGENT_INFO_DATA_NAME.COMPANY_REGISTERED],
});
