export const ENTITY_ACTION_TYPE = {
  ENTITY_LOAD_REQUEST_PENDING:
    'ENTITY_ACTION_TYPE.ENTITY_LOAD_REQUEST_PENDING',
  ENTITY_LOAD_REQUEST_SUCCESS:
    'ENTITY_ACTION_TYPE.ENTITY_REQUEST_LOAD_REQUEST_SUCCESS',
  ENTITY_LOAD_REQUEST_ERROR:
    'ENTITY_ACTION_TYPE.ENTITY_LOAD_REQUEST_ERROR',
};
