export const RISK_RATING_ASSESSMENT_ACTION_TYPE = {
  RISK_RATING_ASSESSMENT_LOAD_REQUEST_PENDING:
    'RISK_RATING_ASSESSMENT_ACTION_TYPE.RISK_RATING_ASSESSMENT_LOAD_REQUEST_PENDING',
  RISK_RATING_ASSESSMENT_LOAD_REQUEST_SUCCESS:
    'RISK_RATING_ASSESSMENT_ACTION_TYPE.RISK_RATING_ASSESSMENT_REQUEST_LOAD_REQUEST_SUCCESS',
  RISK_RATING_ASSESSMENT_LOAD_REQUEST_ERROR:
    'RISK_RATING_ASSESSMENT_ACTION_TYPE.RISK_RATING_ASSESSMENT_LOAD_REQUEST_ERROR',
};
