export const EDIT_ARTICLE_ACTION_TYPE = {
  ARTICLE_LOAD_PENDING: 'EDIT_ARTICLE_ACTION_TYPE.ARTICLE_LOAD_PENDING',
  ARTICLE_LOAD_SUCCESS: 'EDIT_ARTICLE_ACTION_TYPE.ARTICLE_LOAD_SUCCESS',
  ARTICLE_LOAD_ERROR: 'EDIT_ARTICLE_ACTION_TYPE.ARTICLE_LOAD_ERROR',

  ARTICLE_UPDATE_PENDING: 'EDIT_ARTICLE_ACTION_TYPE.ARTICLE_UPDATE_PENDING',
  ARTICLE_UPDATE_SUCCESS: 'EDIT_ARTICLE_ACTION_TYPE.ARTICLE_UPDATE_SUCCESS',
  ARTICLE_UPDATE_ERROR: 'EDIT_ARTICLE_ACTION_TYPE.ARTICLE_UPDATE_ERROR',

  ARTICLE_DELETE_PENDING: 'EDIT_ARTICLE_ACTION_TYPE.ARTICLE_DELETE_PENDING',
  ARTICLE_DELETE_SUCCESS: 'EDIT_ARTICLE_ACTION_TYPE.ARTICLE_DELETE_SUCCESS',
  ARTICLE_DELETE_ERROR: 'EDIT_ARTICLE_ACTION_TYPE.ARTICLE_DELETE_ERROR',
};

export const EDIT_ARTICLE_FIELD_NAME = {
  TITLE: 'title',
  DESCRIPTION: 'description',
  ARTICLE: 'article',
};
