export const THEME_ARBITRATION_ACTION_TYPE = {
  THEME_ARBITRATION_LOAD_REQUEST_PENDING:
    'THEME_ARBITRATION_ACTION_TYPE.THEME_ARBITRATION_LOAD_REQUEST_PENDING',
  THEME_ARBITRATION_LOAD_REQUEST_SUCCESS:
    'THEME_ARBITRATION_ACTION_TYPE.THEME_ARBITRATION_REQUEST_LOAD_REQUEST_SUCCESS',
  THEME_ARBITRATION_LOAD_REQUEST_ERROR:
    'THEME_ARBITRATION_ACTION_TYPE.THEME_ARBITRATION_LOAD_REQUEST_ERROR',
};
