export const BOOK_REVIEW_LIST_ACTION_TYPE = {
<<<<<<< HEAD
  BOOK_REVIEW_LIST_LOAD_REQUEST_PENDING:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_LOAD_REQUEST_PENDING',
  BOOK_REVIEW_LIST_LOAD_REQUEST_SUCCESS:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_REQUEST_LOAD_REQUEST_SUCCESS',
  BOOK_REVIEW_LIST_LOAD_REQUEST_ERROR:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_LOAD_REQUEST_ERROR',
=======
  BOOK_REVIEW_LIST_GET_DATA_REQUEST_PENDING:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_GET_DATA_REQUEST_PENDING',
  BOOK_REVIEW_LIST_GET_DATA_REQUEST_SUCCESS:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_GET_DATA_REQUEST_SUCCESS',
  BOOK_REVIEW_LIST_GET_DATA_REQUEST_ERROR:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_GET_DATA_REQUEST_ERROR',
  BOOK_REVIEW_LIST_GET_DATA_REQUEST_RESET:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_GET_DATA_REQUEST_RESET',
>>>>>>> books-page
};
