export const BOOK_REVIEW_LIST_ACTION_TYPE = {
  BOOK_REVIEW_LIST_GET_DATA_REQUEST_PENDING:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_GET_DATA_REQUEST_PENDING',
  BOOK_REVIEW_LIST_GET_DATA_REQUEST_SUCCESS:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_GET_DATA_REQUEST_SUCCESS',
  BOOK_REVIEW_LIST_GET_DATA_REQUEST_ERROR:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_GET_DATA_REQUEST_ERROR',
  BOOK_REVIEW_LIST_GET_DATA_REQUEST_RESET:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_GET_DATA_REQUEST_RESET',
};
