export const BOOK_REVIEW_LIST_ACTION_TYPE = {
  BOOK_REVIEW_LIST_LOAD_REQUEST_PENDING:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_LOAD_REQUEST_PENDING',
  BOOK_REVIEW_LIST_LOAD_REQUEST_SUCCESS:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_REQUEST_LOAD_REQUEST_SUCCESS',
  BOOK_REVIEW_LIST_LOAD_REQUEST_ERROR:
    'BOOK_REVIEW_LIST_ACTION_TYPE.BOOK_REVIEW_LIST_LOAD_REQUEST_ERROR',
};
