export const COMPANY_INVITE_ACTION_TYPE = {
  COMPANY_INVITE_LOAD_DATA_PENDING:
    'COMPANY_INVITE_ACTION_TYPE.COMPANY_INVITE_LOAD_DATA_PENDING',
  COMPANY_INVITE_LOAD_DATA_SUCCESS:
    'COMPANY_INVITE_ACTION_TYPE.COMPANY_INVITE_LOAD_DATA_SUCCESS',
  COMPANY_INVITE_LOAD_DATA_ERROR:
    'COMPANY_INVITE_ACTION_TYPE.COMPANY_INVITE_LOAD_DATA_ERROR',
  COMPANY_INVITE_LOAD_DATA_RESET:
    'COMPANY_INVITE_ACTION_TYPE.COMPANY_INVITE_LOAD_DATA_RESET',
};

export const COMPANY_INVITE_DATA_NAME = {
  COMPANY_ID: 'companyId',
  COMPANY_NAME: 'companyName',
  USER_ROLE: 'role',
  CREATE_DATE: 'date',
};
export const COMPANY_INVITE_DATA_KEY = {
  COMPANY_ID: 'id',
  COMPANY_NAME: 'name',
  COMPANY_USER: 'companyUser',
  USER_ROLE: 'role',
  CREATE_DATE: 'date',
};
