import { COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME } from './company-account-item-revision-item.constant';
import { convertFormatDate } from '../../lib/common/convert/convert.core';

export const performCompanyAccountItemRevisionItemData = (row) => ({
  [COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.REVISION_COMPANIES]:
    row[COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.REVISION_COMPANIES],

  [COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.REVIEW]:
    row[COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.REVIEW],
  [COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.FILE_REVIEW]:
    row[COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.FILE_REVIEW],
  [COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.STATUS]:
    row[COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.STATUS],
  [COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.PRICE]:
    row[COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.PRICE],
  [COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.NAME]:
    row[COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.NAME],
  [COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.CREATE_DATE]: convertFormatDate(
    row[COMPANY_ACCOUNT_ITEM_REVISION_ITEM_DATA_NAME.CREATE_DATE],
  ),
});
