export const CREATE_ARTICLE_ACTION_TYPE = {
  CREATE_ARTICLE_UPLOAD_PENDING:
    'CREATE_ARTICLE_ACTION_TYPE.CREATE_ARTICLE_UPLOAD_PENDING',
  CREATE_ARTICLE_UPLOAD_SUCCESS:
    'CREATE_ARTICLE_ACTION_TYPE.CREATE_ARTICLE_UPLOAD_SUCCESS',
  CREATE_ARTICLE_UPLOAD_ERROR:
    'CREATE_ARTICLE_ACTION_TYPE.CREATE_ARTICLE_UPLOAD_ERROR',

  ARTICLE_LOAD_PENDING: 'CREATE_ARTICLE_ACTION_TYPE.ARTICLE_LOAD_PENDING',
  ARTICLE_LOAD_SUCCESS: 'CREATE_ARTICLE_ACTION_TYPE.ARTICLE_LOAD_SUCCESS',
  ARTICLE_LOAD_ERROR: 'CREATE_ARTICLE_ACTION_TYPE.ARTICLE_LOAD_ERROR',

  ARTICLE_UPDATE_PENDING: 'CREATE_ARTICLE_ACTION_TYPE.ARTICLE_UPDATE_PENDING',
  ARTICLE_UPDATE_SUCCESS: 'CREATE_ARTICLE_ACTION_TYPE.ARTICLE_UPDATE_SUCCESS',
  ARTICLE_UPDATE_ERROR: 'CREATE_ARTICLE_ACTION_TYPE.ARTICLE_UPDATE_ERROR',

  ARTICLE_DELETE_PENDING: 'ARTICLE_ACTION_TYPE.ARTICLE_DELETE_PENDING',
  ARTICLE_DELETE_SUCCESS: 'ARTICLE_ACTION_TYPE.ARTICLE_DELETE_SUCCESS',
  ARTICLE_DELETE_ERROR: 'ARTICLE_ACTION_TYPE.ARTICLE_DELETE_ERROR',
};

export const ARTICLE_FIELD_NAME = {
  TITLE: 'title',
  DESCRIPTION: 'description',
  ARTICLE: 'article',
};
