import { COMPANY_ACCOUNT_ITEM_INFO_DATA_NAME } from './company-account-item-info.constant';

export const performCompanyAccountItemInfoData = (row) => ({
  [COMPANY_ACCOUNT_ITEM_INFO_DATA_NAME.ID]:
    row[COMPANY_ACCOUNT_ITEM_INFO_DATA_NAME.ID],
  [COMPANY_ACCOUNT_ITEM_INFO_DATA_NAME.NAME]:
    row[COMPANY_ACCOUNT_ITEM_INFO_DATA_NAME.NAME],
  [COMPANY_ACCOUNT_ITEM_INFO_DATA_NAME.INN]:
    row[COMPANY_ACCOUNT_ITEM_INFO_DATA_NAME.INN],
  [COMPANY_ACCOUNT_ITEM_INFO_DATA_NAME.VERIFICATE_INFO]:
    row[COMPANY_ACCOUNT_ITEM_INFO_DATA_NAME.VERIFICATE_INFO],
  [COMPANY_ACCOUNT_ITEM_INFO_DATA_NAME.VERIFICATE_PAYMENT]:
    row[COMPANY_ACCOUNT_ITEM_INFO_DATA_NAME.VERIFICATE_PAYMENT],
});
