export const MY_LAWYER_REQUEST_LIST_ACTION_TYPE = {
  MY_LAWYER_REQUEST_LIST_LOAD_REQUEST_PENDING:
    'MY_LAWYER_REQUEST_LIST_ACTION_TYPE.MY_LAWYER_REQUEST_LIST_LOAD_REQUEST_PENDING',
  MY_LAWYER_REQUEST_LIST_LOAD_REQUEST_SUCCESS:
    'MY_LAWYER_REQUEST_LIST_ACTION_TYPE.MY_LAWYER_REQUEST_LIST_LOAD_REQUEST_SUCCESS',
  MY_LAWYER_REQUEST_LIST_LOAD_REQUEST_ERROR:
    'MY_LAWYER_REQUEST_LIST_ACTION_TYPE.MY_LAWYER_REQUEST_LIST_LOAD_REQUEST_ERROR',
};
