import { COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME } from './company-admin-item-member-list.constant';

export const performCompanyAdminItemMemberListData = (row) => {
  return row[COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.LIST].map((member) => ({
    [COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.FIRSTNAME]:
      member[COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.USER][
        COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.FIRSTNAME
      ],
    [COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.LASTNAME]:
      member[COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.USER][
        COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.LASTNAME
      ],
    [COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.LOGIN]:
      member[COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.USER][
        COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.LOGIN
      ],
    [COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.ROLE]:
      member[COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.ROLE],
    [COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.EMAIL]:
      member[COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.USER][
        COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.EMAIL
      ],
    [COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.PHONE]:
      member[COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.USER][
        COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.PHONE
      ],
    [COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.ID]:
      member[COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.USER][
        COMPANY_ADMIN_ITEM_MEMBER_LIST_DATA_NAME.ID
      ],
  }));
};
