export const MY_COUNTERPARTIES_LIST_ACTION_TYPE = {
  MY_COUNTERPARTIES_LIST_REQUEST_LOAD_LIST_PENDING:
    'MY_COUNTERPARTIES_LIST_ACTION_TYPE.MY_COUNTERPARTIES_LIST_REQUEST_LOAD_LIST_PENDING',
  MY_COUNTERPARTIES_LIST_REQUEST_LOAD_LIST_SUCCESS:
    'MY_COUNTERPARTIES_LIST_ACTION_TYPE.MY_COUNTERPARTIES_LIST_REQUEST_REQUEST_LOAD_LIST_SUCCESS',
  MY_COUNTERPARTIES_LIST_REQUEST_LOAD_LIST_ERROR:
    'MY_COUNTERPARTIES_LIST_ACTION_TYPE.MY_COUNTERPARTIES_LIST_REQUEST_LOAD_LIST_ERROR',
};
