export const HEADER_ACTION_TYPE = {
  HEADER_NOTIFICATION_LOAD_REQUEST_PENDING:
    'HEADER_ACTION_TYPE.HEADER_NOTIFICATION_LOAD_REQUEST_PENDING',
  HEADER_NOTIFICATION_LOAD_REQUEST_SUCCESS:
    'HEADER_ACTION_TYPE.HEADER_NOTIFICATION_LOAD_REQUEST_SUCCESS',
  HEADER_NOTIFICATION_LOAD_REQUEST_ERROR:
    'HEADER_ACTION_TYPE.HEADER_NOTIFICATION_LOAD_REQUEST_ERROR',
};
export const HEADER_NOTIFICATION_DATA_KEY = {
  PROP: 'PROP',
};
export const HEADER_NOTIFICATION_DATA_NAME = {
  PROP: 'PROP',
};
