import { SUPPORT_FORM_CREATE_REQUEST_FIELD_KEY } from './frame/support-form-create-request';

export const SUPPORT_CREATE_REQUEST_FIELD_NAME = {
  PROBLEM_CATEGORY: 'problemCategory',
  PROBLEM_OUTLINE: 'problemOutline',
  PROBLEM_DESCRIPTION: 'problemDescription',
};

export const SUPPORT_FORM_CREATE_REQUEST_FIELD_NAME = {
  [SUPPORT_FORM_CREATE_REQUEST_FIELD_KEY.PROBLEM_CATEGORY]:
    SUPPORT_CREATE_REQUEST_FIELD_NAME.PROBLEM_CATEGORY,
  [SUPPORT_FORM_CREATE_REQUEST_FIELD_KEY.PROBLEM_OUTLINE]:
    SUPPORT_CREATE_REQUEST_FIELD_NAME.PROBLEM_OUTLINE,
  [SUPPORT_FORM_CREATE_REQUEST_FIELD_KEY.PROBLEM_DESCRIPTION]:
    SUPPORT_CREATE_REQUEST_FIELD_NAME.PROBLEM_DESCRIPTION,
};
