import {
  SUPPORT_CREATE_REQUEST_DATA_NAME,
  SUPPORT_CREATE_REQUEST_FIELD_NAME,
} from './support-create-request.type';

export const convertSupportCreateRequestFormData = (data) => ({
  [SUPPORT_CREATE_REQUEST_DATA_NAME.CATEGORY]:
    data[SUPPORT_CREATE_REQUEST_FIELD_NAME.PROBLEM_CATEGORY],
  [SUPPORT_CREATE_REQUEST_DATA_NAME.BRIEF]:
    data[SUPPORT_CREATE_REQUEST_FIELD_NAME.PROBLEM_OUTLINE],
  [SUPPORT_CREATE_REQUEST_DATA_NAME.EXPLICITLY]:
    data[SUPPORT_CREATE_REQUEST_FIELD_NAME.PROBLEM_DESCRIPTION],
});
