import { SUPPORT_FORM_CREATE_REQUEST_FIELD_KEY } from './frame/support-form-create-request';

export const SUPPORT_CREATE_REQUEST_FIELD_NAME = {
  PROBLEM_CATEGORY: 'problemCategory',
  PROBLEM_OUTLINE: 'problemOutline',
  PROBLEM_DESCRIPTION: 'problemDescription',
};

export const SUPPORT_FORM_CREATE_REQUEST_FIELD_NAME = {
  [SUPPORT_FORM_CREATE_REQUEST_FIELD_KEY.PROBLEM_CATEGORY]:
    SUPPORT_CREATE_REQUEST_FIELD_NAME.PROBLEM_CATEGORY,
  [SUPPORT_FORM_CREATE_REQUEST_FIELD_KEY.PROBLEM_OUTLINE]:
    SUPPORT_CREATE_REQUEST_FIELD_NAME.PROBLEM_OUTLINE,
  [SUPPORT_FORM_CREATE_REQUEST_FIELD_KEY.PROBLEM_DESCRIPTION]:
    SUPPORT_CREATE_REQUEST_FIELD_NAME.PROBLEM_DESCRIPTION,
};

export const SUPPORT_CREATE_REQUEST_ACTION_TYPE = {
  SUPPORT_FORM_CREATE_REQUEST_UPLOAD_PENDING:
    'SUPPORT_CREATE_REQUEST_ACTION_TYPE.SUPPORT_FORM_CREATE_REQUEST_UPLOAD_PENDING',
  SUPPORT_FORM_CREATE_REQUEST_UPLOAD_SUCCESS:
    'SUPPORT_CREATE_REQUEST_ACTION_TYPE.SUPPORT_FORM_CREATE_REQUEST_UPLOAD_SUCCESS',
  SUPPORT_FORM_CREATE_REQUEST_UPLOAD_ERROR:
    'SUPPORT_CREATE_REQUEST_ACTION_TYPE.SUPPORT_FORM_CREATE_REQUEST_UPLOAD_ERROR',
  SUPPORT_FORM_CREATE_REQUEST_UPLOAD_RESET:
    'SUPPORT_CREATE_REQUEST_ACTION_TYPE.SUPPORT_FORM_CREATE_REQUEST_UPLOAD_RESET',
};

export const SUPPORT_CREATE_REQUEST_DATA_NAME = {
  CATEGORY: 'categoryId',
  BRIEF: 'brief',
  EXPLICITLY: 'explicitly',
};
