export const DASHBOARD_ACTION_TYPE = {
  DASHBOARD_LOAD_REQUEST_PENDING:
    'DASHBOARD_ACTION_TYPE.DASHBOARD_LOAD_REQUEST_PENDING',
  DASHBOARD_LOAD_REQUEST_SUCCESS:
    'DASHBOARD_ACTION_TYPE.DASHBOARD_REQUEST_LOAD_REQUEST_SUCCESS',
  DASHBOARD_LOAD_REQUEST_ERROR:
    'DASHBOARD_ACTION_TYPE.DASHBOARD_LOAD_REQUEST_ERROR',
};
