export const DIALOG_LIST_HEADER_SELECT_OPTIONS = [
  { id: 0, tid: 'DIALOGS.DIALOG_LIST.SELECT_OPTION.0' },
  { id: 1, tid: 'DIALOGS.DIALOG_LIST.SELECT_OPTION.1' },
  { id: 2, tid: 'DIALOGS.DIALOG_LIST.SELECT_OPTION.2' },
];
