import { BALANCE_FORM_DEPOSIT_FIELD_KEY } from './frame/balance-form-deposit';

export const BALANCE_DEPOSIT_FIELD_NAME = {
  PAYMENT_METHOD: 'paymentMethod',
  DEPOSIT_AMOUNT: 'depositAmount',
};

export const BALANCE_FORM_DEPOSIT_FIELD_NAME = {
  [BALANCE_FORM_DEPOSIT_FIELD_KEY.DEPOSIT_AMOUNT]:
    BALANCE_DEPOSIT_FIELD_NAME.DEPOSIT_AMOUNT,
  [BALANCE_FORM_DEPOSIT_FIELD_KEY.PAYMENT_METHOD]:
    BALANCE_DEPOSIT_FIELD_NAME.PAYMENT_METHOD,
};
