import { BALANCE_FORM_DEPOSIT_FIELD_KEY } from './frame/balance-form-deposit';

export const BALANCE_DEPOSIT_FIELD_NAME = {
  PAYMENT_METHOD: 'paymentMethod',
  DEPOSIT_AMOUNT: 'depositAmount',
};

export const BALANCE_FORM_DEPOSIT_FIELD_NAME = {
  [BALANCE_FORM_DEPOSIT_FIELD_KEY.DEPOSIT_AMOUNT]:
    BALANCE_DEPOSIT_FIELD_NAME.DEPOSIT_AMOUNT,
  [BALANCE_FORM_DEPOSIT_FIELD_KEY.PAYMENT_METHOD]:
    BALANCE_DEPOSIT_FIELD_NAME.PAYMENT_METHOD,
};

export const BALANCE_DEPOSIT_ACTION_TYPE = {
  BALANCE_FORM_DEPOSIT_UPLOAD_PENDING:
    'BALANCE_DEPOSIT_ACTION_TYPE.BALANCE_FORM_DEPOSIT_UPLOAD_PENDING',
  BALANCE_FORM_DEPOSIT_UPLOAD_SUCCESS:
    'BALANCE_DEPOSIT_ACTION_TYPE.BALANCE_FORM_DEPOSIT_UPLOAD_SUCCESS',
  BALANCE_FORM_DEPOSIT_UPLOAD_ERROR:
    'BALANCE_DEPOSIT_ACTION_TYPE.BALANCE_FORM_DEPOSIT_UPLOAD_ERROR',
  BALANCE_FORM_DEPOSIT_UPLOAD_RESET:
    'BALANCE_DEPOSIT_ACTION_TYPE.BALANCE_FORM_DEPOSIT_UPLOAD_RESET',
};

export const BALANCE_DEPOSIT_DATA_NAME = {
  PAYMENT_METHOD: 'paymentMethod',
  DEPOSIT: 'deposit',
};
