import {
  MY_COMPANIES_ADD_COMPANY_DATA_NAME,
  MY_COMPANIES_ADD_COMPANY_FIELD_NAME,
} from './my-companies-add-company.type';

export const convertAddCompanyFormData = (data) => ({
  [MY_COMPANIES_ADD_COMPANY_DATA_NAME.NAME]:
    data[MY_COMPANIES_ADD_COMPANY_FIELD_NAME.NAME],
  [MY_COMPANIES_ADD_COMPANY_DATA_NAME.INN]:
    data[MY_COMPANIES_ADD_COMPANY_FIELD_NAME.INN],
});
