import { SETTINGS_FORM_CHANGE_PASSWORD_FIELD_KEY } from './frame/settings-form-change-password';

export const SETTINGS_PASSWORD_FIELD_NAME = {
  NEW_PASSWORD: 'newPassword',
  REPEAT_NEW_PASSWORD: 'repeatNewPassword',
  OLD_PASSWORD: 'oldPassword',
};

export const SETTINGS_FORM_CHANGE_PASSWORD_FIELD_NAME = {
  [SETTINGS_FORM_CHANGE_PASSWORD_FIELD_KEY.NEW_PASSWORD]:
    SETTINGS_PASSWORD_FIELD_NAME.NEW_PASSWORD,
  [SETTINGS_FORM_CHANGE_PASSWORD_FIELD_KEY.REPEAT_NEW_PASSWORD]:
    SETTINGS_PASSWORD_FIELD_NAME.REPEAT_NEW_PASSWORD,
  [SETTINGS_FORM_CHANGE_PASSWORD_FIELD_KEY.OLD_PASSWORD]:
    SETTINGS_PASSWORD_FIELD_NAME.OLD_PASSWORD,
};

export const SETTINGS_PASSWORD_ACTION_TYPE = {
  SETTINGS_FORM_CHANGE_PASSWORD_UPLOAD_SUCCESS:
    'SETTINGS_FORM_CHANGE_PASSWORD_UPLOAD_SUCCESS',
  SETTINGS_FORM_CHANGE_PASSWORD_UPLOAD_PENDING:
    'SETTINGS_FORM_CHANGE_PASSWORD_UPLOAD_PENDING',
  SETTINGS_FORM_CHANGE_PASSWORD_UPLOAD_ERROR:
    'SETTINGS_FORM_CHANGE_PASSWORD_UPLOAD_ERROR',
  SETTINGS_FORM_CHANGE_PASSWORD_UPLOAD_RESET:
    'SETTINGS_FORM_CHANGE_PASSWORD_UPLOAD_RESET',
};

export const SETTINGS_PASSWORD_DATA_NAME = {
  NEW_PASSWORD: 'newPassword',
  PASSWORD: 'password',
};
