import { SETTINGS_FORM_CHANGE_PASSWORD_FIELD_KEY } from './frame/settings-form-change-password';

export const SETTINGS_PASSWORD_FIELD_NAME = {
  NEW_PASSWORD: 'new-password',
  REPEAT_NEW_PASSWORD: 'repeat-new-password',
  OLD_PASSWORD: 'old-password',
};

export const SETTINGS_FORM_CHANGE_PASSWORD_FIELD_NAME = {
  [SETTINGS_FORM_CHANGE_PASSWORD_FIELD_KEY.NEW_PASSWORD]:
    SETTINGS_PASSWORD_FIELD_NAME.NEW_PASSWORD,
  [SETTINGS_FORM_CHANGE_PASSWORD_FIELD_KEY.REPEAT_NEW_PASSWORD]:
    SETTINGS_PASSWORD_FIELD_NAME.REPEAT_NEW_PASSWORD,
  [SETTINGS_FORM_CHANGE_PASSWORD_FIELD_KEY.OLD_PASSWORD]:
    SETTINGS_PASSWORD_FIELD_NAME.OLD_PASSWORD,
};
