import { PHONE_VERIFICATION_INFO_FORM_FIELD_KEY } from './frame/phone-vefirication-info-form';

export const AUTH_PHONE_VERIFICATION_INFO_FIELD_NAME = {
  VERIFICATION_CODE: 'verificationCode',
};

export const PHONE_VERIFICATION_INFO_FORM_FIELD_NAME = {
  [PHONE_VERIFICATION_INFO_FORM_FIELD_KEY.VERIFICATION_CODE]:
    AUTH_PHONE_VERIFICATION_INFO_FIELD_NAME.VERIFICATION_CODE,
};
