export const REFERRAL_ACTION_TYPE = {
  REFERRAL_LOAD_REQUEST_PENDING:
    'REFERRAL_ACTION_TYPE.REFERRAL_LOAD_REQUEST_PENDING',
  REFERRAL_LOAD_REQUEST_SUCCESS:
    'REFERRAL_ACTION_TYPE.REFERRAL_REQUEST_LOAD_REQUEST_SUCCESS',
  REFERRAL_LOAD_REQUEST_ERROR:
    'REFERRAL_ACTION_TYPE.REFERRAL_LOAD_REQUEST_ERROR',
};
