import { NEW_LAWYER_REQUEST_FORM_FIELD_KEY } from './frame/new-lawyer-request-form';

export const NEW_LAWYER_REQUEST_FIELD_NAME = {
  QUESTION_CATEGORY: 'questionCategory',
  YOUR_QUESTION: 'yourQuestion',
  PROBLEM_DESCRIPTION: 'problemDescription',
};

export const NEW_LAWYER_REQUEST_FORM_FIELD_NAME = {
  [NEW_LAWYER_REQUEST_FORM_FIELD_KEY.QUESTION_CATEGORY]: NEW_LAWYER_REQUEST_FIELD_NAME.QUESTION_CATEGORY,
  [NEW_LAWYER_REQUEST_FORM_FIELD_KEY.YOUR_QUESTION]: NEW_LAWYER_REQUEST_FIELD_NAME.YOUR_QUESTION,
  [NEW_LAWYER_REQUEST_FORM_FIELD_KEY.PROBLEM_DESCRIPTION]: NEW_LAWYER_REQUEST_FIELD_NAME.PROBLEM_DESCRIPTION,
};

export const LAWYER_REQUEST_ACTION_TYPE = {
  LAWYER_REQUEST_LOAD_REQUEST_PENDING:
    'LAWYER_REQUEST_ACTION_TYPE.LAWYER_REQUEST_LOAD_REQUEST_PENDING',
  LAWYER_REQUEST_LOAD_REQUEST_SUCCESS:
    'LAWYER_REQUEST_ACTION_TYPE.LAWYER_REQUEST_REQUEST_LOAD_REQUEST_SUCCESS',
  LAWYER_REQUEST_LOAD_REQUEST_ERROR:
    'LAWYER_REQUEST_ACTION_TYPE.LAWYER_REQUEST_LOAD_REQUEST_ERROR',
};
