export const MY_LEGAL_ENTITIES_LIST_ACTION_TYPE = {
  MY_LEGAL_ENTITIES_LIST_LOAD_REQUEST_PENDING:
    'MY_LEGAL_ENTITIES_LIST_ACTION_TYPE.MY_LEGAL_ENTITIES_LIST_LOAD_REQUEST_PENDING',
  MY_LEGAL_ENTITIES_LIST_LOAD_REQUEST_SUCCESS:
    'MY_LEGAL_ENTITIES_LIST_ACTION_TYPE.MY_LEGAL_ENTITIES_LIST_REQUEST_LOAD_REQUEST_SUCCESS',
  MY_LEGAL_ENTITIES_LIST_LOAD_REQUEST_ERROR:
    'MY_LEGAL_ENTITIES_LIST_ACTION_TYPE.MY_LEGAL_ENTITIES_LIST_LOAD_REQUEST_ERROR',
};
