export const PARTICIPANTS_ACTION_TYPE = {
  PARTICIPANTS_LOAD_REQUEST_PENDING:
    'PARTICIPANTS_ACTION_TYPE.PARTICIPANTS_LOAD_REQUEST_PENDING',
  PARTICIPANTS_LOAD_REQUEST_SUCCESS:
    'PARTICIPANTS_ACTION_TYPE.PARTICIPANTS_REQUEST_LOAD_REQUEST_SUCCESS',
  PARTICIPANTS_LOAD_REQUEST_ERROR:
    'PARTICIPANTS_ACTION_TYPE.PARTICIPANTS_LOAD_REQUEST_ERROR',
};
