export const BALANCE_ACTIVITY_ACTION_TYPE = {
  BALANCE_ACTIVITY_LOAD_REQUEST_PENDING:
    'BALANCE_ACTIVITY_ACTION_TYPE.BALANCE_ACTIVITY_LOAD_REQUEST_PENDING',
  BALANCE_ACTIVITY_LOAD_REQUEST_SUCCESS:
    'BALANCE_ACTIVITY_ACTION_TYPE.BALANCE_ACTIVITY_REQUEST_LOAD_REQUEST_SUCCESS',
  BALANCE_ACTIVITY_LOAD_REQUEST_ERROR:
    'BALANCE_ACTIVITY_ACTION_TYPE.BALANCE_ACTIVITY_LOAD_REQUEST_ERROR',
};
