export const AUTH_VERIFICATION_EMAIL_ACTION_TYPE = {
  AUTH_FORM_VERIFICATION_EMAIL_UPLOAD_PENDING:
    'AUTH_FORM_VERIFICATION_EMAIL_UPLOAD_PENDING',
  AUTH_FORM_VERIFICATION_EMAIL_UPLOAD_SUCCESS:
    'AUTH_FORM_VERIFICATION_EMAIL_UPLOAD_SUCCESS',
  AUTH_FORM_VERIFICATION_EMAIL_UPLOAD_ERROR:
    'AUTH_FORM_VERIFICATION_EMAIL_UPLOAD_ERROR',
  AUTH_FORM_VERIFICATION_EMAIL_UPLOAD_RESET:
    'AUTH_FORM_VERIFICATION_EMAIL_UPLOAD_RESET',
};
