import { COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME } from './company-admin-unregistered-list.constant';

export const performCompanyAdminUnregisteredListRowData = (row) => {
  return row.map((company) => ({
    [COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.ID]: company[COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.ID],
    [COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.NAME]:
      company[COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.NAME],
    [COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.INN]:
      company[COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.INN],
    [COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.VERIFICATE_INFO]:
      company[COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.VERIFICATE_INFO],
    [COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.VERIFICATE_PAYMENT]:
      company[COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.VERIFICATE_PAYMENT],
    [COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.AMOUNT]:
      (company[COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.COMPANY_BALANCE] ?? {})[COMPANY_ADMIN_UNREGISTERED_LIST_DATA_NAME.AMOUNT] ?? 0,
  }));
};
