import { convertFormatDate } from '../../lib/common/convert/convert.core';
import { USER_ADMIN_LIST_DATA_NAME } from './user-admin-list.constant';

export const performUserAdminListRowData = (row) => {
  return row[USER_ADMIN_LIST_DATA_NAME.LIST].map((user) => ({
    [USER_ADMIN_LIST_DATA_NAME.ID]: user[USER_ADMIN_LIST_DATA_NAME.ID],
    [USER_ADMIN_LIST_DATA_NAME.LOGIN]: user[USER_ADMIN_LIST_DATA_NAME.LOGIN],
    [USER_ADMIN_LIST_DATA_NAME.FIRSTNAME]:
      user[USER_ADMIN_LIST_DATA_NAME.FIRSTNAME],
    [USER_ADMIN_LIST_DATA_NAME.LASTNAME]:
      user[USER_ADMIN_LIST_DATA_NAME.LASTNAME],
    [USER_ADMIN_LIST_DATA_NAME.PHONE]: user[USER_ADMIN_LIST_DATA_NAME.PHONE],
    [USER_ADMIN_LIST_DATA_NAME.ROLE]: user[USER_ADMIN_LIST_DATA_NAME.ROLE],
    [USER_ADMIN_LIST_DATA_NAME.CONFIRM_EMAIL]:
      user[USER_ADMIN_LIST_DATA_NAME.CONFIRM_EMAIL],
    [USER_ADMIN_LIST_DATA_NAME.CONFIRM_PHONE]:
      user[USER_ADMIN_LIST_DATA_NAME.CONFIRM_PHONE],
    [USER_ADMIN_LIST_DATA_NAME.EMAIL]: user[USER_ADMIN_LIST_DATA_NAME.EMAIL],
    [USER_ADMIN_LIST_DATA_NAME.CRATE_DATE]: convertFormatDate(
      user[USER_ADMIN_LIST_DATA_NAME.CRATE_DATE],
    ),
  }));
};
