import { COMPANY_ADMIN_LIST_DATA_NAME } from './company-admin-list.constant';

export const performCompanyAdminListRowData = (row) => {
  return row[COMPANY_ADMIN_LIST_DATA_NAME.LIST].map((company) => ({
    [COMPANY_ADMIN_LIST_DATA_NAME.ID]: company[COMPANY_ADMIN_LIST_DATA_NAME.ID],
    [COMPANY_ADMIN_LIST_DATA_NAME.NAME]:
      company[COMPANY_ADMIN_LIST_DATA_NAME.NAME],
    [COMPANY_ADMIN_LIST_DATA_NAME.INN]:
      company[COMPANY_ADMIN_LIST_DATA_NAME.INN],
    [COMPANY_ADMIN_LIST_DATA_NAME.VERIFICATE_INFO]:
      company[COMPANY_ADMIN_LIST_DATA_NAME.VERIFICATE_INFO],
    [COMPANY_ADMIN_LIST_DATA_NAME.VERIFICATE_PAYMENT]:
      company[COMPANY_ADMIN_LIST_DATA_NAME.VERIFICATE_PAYMENT],
    [COMPANY_ADMIN_LIST_DATA_NAME.AMOUNT]:
      company[COMPANY_ADMIN_LIST_DATA_NAME.COMPANY_BALANCE][
        COMPANY_ADMIN_LIST_DATA_NAME.AMOUNT
      ],
  }));
};
