export const NEWS_ARTICLE_ACTION_TYPE = {
  NEWS_ARTICLE_LOAD_REQUEST_PENDING:
    'NEWS_ARTICLE_ACTION_TYPE.NEWS_ARTICLE_LOAD_REQUEST_PENDING',
  NEWS_ARTICLE_LOAD_REQUEST_SUCCESS:
    'NEWS_ARTICLE_ACTION_TYPE.NEWS_ARTICLE_REQUEST_LOAD_REQUEST_SUCCESS',
  NEWS_ARTICLE_LOAD_REQUEST_ERROR:
    'NEWS_ARTICLE_ACTION_TYPE.NEWS_ARTICLE_LOAD_REQUEST_ERROR',
};
