import { AUTH_SIGNUP_DATA_NAME } from './auth-signup.constant';

export const convertAuthSignupFormData = (data) => ({
  [AUTH_SIGNUP_DATA_NAME.LOGIN]: data[AUTH_SIGNUP_DATA_NAME.LOGIN],
  [AUTH_SIGNUP_DATA_NAME.PASSWORD]: data[AUTH_SIGNUP_DATA_NAME.PASSWORD],
  [AUTH_SIGNUP_DATA_NAME.EMAIL]: data[AUTH_SIGNUP_DATA_NAME.EMAIL],
  [AUTH_SIGNUP_DATA_NAME.PHONE]: data[AUTH_SIGNUP_DATA_NAME.PHONE],
  [AUTH_SIGNUP_DATA_NAME.FIRST_NAME]: data[AUTH_SIGNUP_DATA_NAME.FIRST_NAME],
  [AUTH_SIGNUP_DATA_NAME.LAST_NAME]: data[AUTH_SIGNUP_DATA_NAME.LAST_NAME],
});
