import { SETTINGS_FORM_CHANGE_EMAIL_NOTIFICATION_FIELD_KEY } from './frame/settings-form-change-email-notification';

export const SETTINGS_NOTIFICATION_FIELD_NAME = {
  EMAIL: 'email',
};

export const SETTINGS_FORM_CHANGE_EMAIL_NOTIFICATION_FIELD_NAME = {
  [SETTINGS_FORM_CHANGE_EMAIL_NOTIFICATION_FIELD_KEY.EMAIL]:
    SETTINGS_NOTIFICATION_FIELD_NAME.EMAIL,
};
