import { SETTINGS_FORM_CHANGE_PHONE_FIELD_KEY } from './frame/settings-form-change-phone';

export const SETTINGS_PHONE_FIELD_NAME = {
  PHONE_NUMBER: 'phone',
  PASSWORD: 'password',
};

export const SETTINGS_FORM_CHANGE_PHONE_FIELD_NAME = {
  [SETTINGS_FORM_CHANGE_PHONE_FIELD_KEY.PHONE_NUMBER]:
    SETTINGS_PHONE_FIELD_NAME.PHONE_NUMBER,
  [SETTINGS_FORM_CHANGE_PHONE_FIELD_KEY.PASSWORD]:
    SETTINGS_PHONE_FIELD_NAME.PASSWORD,
};
