import { COMPANY_ACCOUNT_ITEM_KONTRAGENT_LIST_DATA_NAME } from './company-account-item-kontragent-list.constant';

export const convertCompanyAccountItemKontragentList = (d) => {
  return d.map((company) => ({
    [COMPANY_ACCOUNT_ITEM_KONTRAGENT_LIST_DATA_NAME.ID]:
      company[COMPANY_ACCOUNT_ITEM_KONTRAGENT_LIST_DATA_NAME.ID],
    [COMPANY_ACCOUNT_ITEM_KONTRAGENT_LIST_DATA_NAME.NAME]:
      company[COMPANY_ACCOUNT_ITEM_KONTRAGENT_LIST_DATA_NAME.NAME],
    [COMPANY_ACCOUNT_ITEM_KONTRAGENT_LIST_DATA_NAME.INN]:
      company[COMPANY_ACCOUNT_ITEM_KONTRAGENT_LIST_DATA_NAME.CONTRACTOR][
        COMPANY_ACCOUNT_ITEM_KONTRAGENT_LIST_DATA_NAME.INN
      ],
  }));
};
