export const RED_ZONE_INFORMATION_ACTION_TYPE = {
  RED_ZONE_INFORMATION_LOAD_REQUEST_PENDING:
    'RED_ZONE_INFORMATION_ACTION_TYPE.RED_ZONE_INFORMATION_LOAD_REQUEST_PENDING',
  RED_ZONE_INFORMATION_LOAD_REQUEST_SUCCESS:
    'RED_ZONE_INFORMATION_ACTION_TYPE.RED_ZONE_INFORMATION_REQUEST_LOAD_REQUEST_SUCCESS',
  RED_ZONE_INFORMATION_LOAD_REQUEST_ERROR:
    'RED_ZONE_INFORMATION_ACTION_TYPE.RED_ZONE_INFORMATION_LOAD_REQUEST_ERROR',
};
