export const VERIFICATIONS_ACTION_TYPE = {
  VERIFICATIONS_LOAD_REQUEST_PENDING:
    'VERIFICATIONS_ACTION_TYPE.VERIFICATIONS_LOAD_REQUEST_PENDING',
  VERIFICATIONS_LOAD_REQUEST_SUCCESS:
    'VERIFICATIONS_ACTION_TYPE.VERIFICATIONS_REQUEST_LOAD_REQUEST_SUCCESS',
  VERIFICATIONS_LOAD_REQUEST_ERROR:
    'VERIFICATIONS_ACTION_TYPE.VERIFICATIONS_LOAD_REQUEST_ERROR',
};
