export const DIALOG_LAWYER_ACTION_TYPE = {
  DIALOG_LAWYER_LOAD_REQUEST_PENDING:
    'DIALOG_LAWYER_ACTION_TYPE.DIALOG_LAWYER_LOAD_REQUEST_PENDING',
  DIALOG_LAWYER_LOAD_REQUEST_SUCCESS:
    'DIALOG_LAWYER_ACTION_TYPE.DIALOG_LAWYER_REQUEST_LOAD_REQUEST_SUCCESS',
  DIALOG_LAWYER_LOAD_REQUEST_ERROR:
    'DIALOG_LAWYER_ACTION_TYPE.DIALOG_LAWYER_LOAD_REQUEST_ERROR',
};
