export const ARBITRATION_CASES_ACTION_TYPE = {
  ARBITRATION_CASES_LOAD_REQUEST_PENDING:
    'ARBITRATION_CASES_ACTION_TYPE.ARBITRATION_CASES_LOAD_REQUEST_PENDING',
  ARBITRATION_CASES_LOAD_REQUEST_SUCCESS:
    'ARBITRATION_CASES_ACTION_TYPE.ARBITRATION_CASES_REQUEST_LOAD_REQUEST_SUCCESS',
  ARBITRATION_CASES_LOAD_REQUEST_ERROR:
    'ARBITRATION_CASES_ACTION_TYPE.ARBITRATION_CASES_LOAD_REQUEST_ERROR',
};
