export const MY_COMPANIES_REVIEW_COMPANY_LIST_ACTION_TYPE = {
  MY_COMPANIES_REVIEW_COMPANY_LIST_LOAD_COMPANIES_PENDING:
    'MY_COMPANIES_REVIEW_COMPANY_LIST_ACTION_TYPE.MY_COMPANIES_REVIEW_COMPANY_LIST_LOAD_COMPANIES_PENDING',
  MY_COMPANIES_REVIEW_COMPANY_LIST_LOAD_COMPANIES_SUCCESS:
    'MY_COMPANIES_REVIEW_COMPANY_LIST_ACTION_TYPE.MY_COMPANIES_REVIEW_COMPANY_LIST_LOAD_COMPANIES_SUCCESS',
  MY_COMPANIES_REVIEW_COMPANY_LIST_LOAD_COMPANIES_ERROR:
    'MY_COMPANIES_REVIEW_COMPANY_LIST_ACTION_TYPE.MY_COMPANIES_REVIEW_COMPANY_LIST_LOAD_COMPANIES_ERROR',
  MY_COMPANIES_REVIEW_COMPANY_LIST_LOAD_COMPANIES_RESET:
    'MY_COMPANIES_REVIEW_COMPANY_LIST_ACTION_TYPE.MY_COMPANIES_REVIEW_COMPANY_LIST_LOAD_COMPANIES_RESET',
};

export const MY_COMPANIES_REVIEW_COMPANY_LIST_DATA_NAME = {
  COMPANY_ID: 'companyId',
  COMPANY_NAME: 'companyName',
  USER_ROLE: 'role',
  CREATE_DATE: 'date',
};
export const MY_COMPANIES_REVIEW_COMPANY_LIST_DATA_KEY = {
  COMPANY_ID: 'id',
  COMPANY_NAME: 'name',
  COMPANY_USER: 'companyUser',
  USER_ROLE: 'role',
  CREATE_DATE: 'date',
};
