export const REVIEWS_ACTION_TYPE = {
  REVIEWS_LOAD_REQUEST_PENDING:
    'REVIEWS_ACTION_TYPE.REVIEWS_LOAD_REQUEST_PENDING',
  REVIEWS_LOAD_REQUEST_SUCCESS:
    'REVIEWS_ACTION_TYPE.REVIEWS_REQUEST_LOAD_REQUEST_SUCCESS',
  REVIEWS_LOAD_REQUEST_ERROR:
    'REVIEWS_ACTION_TYPE.REVIEWS_LOAD_REQUEST_ERROR',
};
