export const DIALOG_PERSONAL_ACTION_TYPE = {
  DIALOG_PERSONAL_LOAD_REQUEST_PENDING:
    'DIALOG_PERSONAL_ACTION_TYPE.DIALOG_PERSONAL_LOAD_REQUEST_PENDING',
  DIALOG_PERSONAL_LOAD_REQUEST_SUCCESS:
    'DIALOG_PERSONAL_ACTION_TYPE.DIALOG_PERSONAL_REQUEST_LOAD_REQUEST_SUCCESS',
  DIALOG_PERSONAL_LOAD_REQUEST_ERROR:
    'DIALOG_PERSONAL_ACTION_TYPE.DIALOG_PERSONAL_LOAD_REQUEST_ERROR',
};
