export const MY_REQUESTS_JURISTS_LIST_ACTION_TYPE = {
  MY_REQUESTS_JURISTS_LIST_LOAD_REQUEST_PENDING:
    'MY_REQUESTS_JURISTS_LIST_ACTION_TYPE.MY_REQUESTS_JURISTS_LIST_LOAD_REQUEST_PENDING',
  MY_REQUESTS_JURISTS_LIST_LOAD_REQUEST_SUCCESS:
    'MY_REQUESTS_JURISTS_LIST_ACTION_TYPE.MY_REQUESTS_JURISTS_LIST_LOAD_REQUEST_SUCCESS',
  MY_REQUESTS_JURISTS_LIST_LOAD_REQUEST_ERROR:
    'MY_REQUESTS_JURISTS_LIST_ACTION_TYPE.MY_REQUESTS_JURISTS_LIST_LOAD_REQUEST_ERROR',
};
