import { ACCOUNT_INFO_FORM_FIELD_KEY } from '../auth-account-info-form/frame/account-info-form';

export const AUTH_ACCOUNT_INFO_FORM_FIELD_NAME = {
  FULLNAME_NAME: 'fullname',
  COMPANY_INFO_FORM_FIELDS: 'companyInfoFormFields',
  COMPANY_NAME: 'companyName',
  COMPANY_INN: 'companyINN',
  POSITION_IN_COMPANY: 'positionInCompany',
};

export const ACCOUNT_INFO_FORM_FIELD_NAME = {
  [ACCOUNT_INFO_FORM_FIELD_KEY.FULLNAME_NAME]: AUTH_ACCOUNT_INFO_FORM_FIELD_NAME.FULLNAME_NAME,
  [ACCOUNT_INFO_FORM_FIELD_KEY.COMPANY_INFO_FORM_FIELDS]: AUTH_ACCOUNT_INFO_FORM_FIELD_NAME.COMPANY_INFO_FORM_FIELDS,
  [ACCOUNT_INFO_FORM_FIELD_KEY.COMPANY_NAME]: AUTH_ACCOUNT_INFO_FORM_FIELD_NAME.COMPANY_NAME,
  [ACCOUNT_INFO_FORM_FIELD_KEY.COMPANY_INN]: AUTH_ACCOUNT_INFO_FORM_FIELD_NAME.COMPANY_INN,
  [ACCOUNT_INFO_FORM_FIELD_KEY.POSITION_IN_COMPANY]: AUTH_ACCOUNT_INFO_FORM_FIELD_NAME.POSITION_IN_COMPANY,
};
