export const ARTICLE_ACTION_TYPE = {
  ARTICLE_LOAD_PENDING: 'ARTICLE_ACTION_TYPE.ARTICLE_LOAD_PENDING',
  ARTICLE_LOAD_SUCCESS: 'ARTICLE_ACTION_TYPE.ARTICLE_LOAD_SUCCESS',
  ARTICLE_LOAD_ERROR: 'ARTICLE_ACTION_TYPE.ARTICLE_LOAD_ERROR'
};